name: doc_easy_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.2+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: any
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^7.6.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.5
  pretty_dio_logger: ^1.4.0
  easy_localization: ^3.0.7
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.11.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
