default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution" 
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:4484815169:android:f38ea240823b243a3fa9c0",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      firebase_cli_token:"1//09P7G35Iz5HbZCgYIARAAGAkSNgF-L9IrlL8cm8KOZmIU4R1edN9vLXNGXRdouMWOj7wlOZA5LgGu3wnW5YUips__nNycnA-Mhw",
      release_notes: "First release",
      testers: "abdullah.m.z2005@gmail.com"
    )
  end
end
